[package]
name = "micro-shell"
version = "0.1.0"
authors = ["Dylane-SILVA <62027846+Dylane-SILVA@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
